### ISSUE TITLE
HOTFIX 2: Restrict payment types to Tap only

### ISSUE THREAD

**Issue by shleeable** [sighmon/OpenDonation#2]
https://docs.connect.squareup.com/api/point-of-sale/android/com/squareup/sdk/pos/ChargeRequest.Builder.html#restrictTendersTo-java.util.Collection-

https://docs.connect.squareup.com/api/point-of-sale/android/com/squareup/sdk/pos/ChargeRequest.TenderType.html#CARD

**Comment by sighmon** [comment]
Fixed in a8644af
