### ISSUE TITLE
FEATURE 3: Theme

### ISSUE THREAD

**Issue by shleeable** [sighmon/OpenDonation#7]
This kind of depends on how we handle the scroller - but I'd like to be able to theme the application

Min: https://generozity.com.au/ purple

ok: maybe an animated cycle with the logo or something

better: fully themed animated application.

Maybe if half of the app was interaction and the second half was just "empty space" for artwork to cycle thru

**Comment by shleeable** [comment]
![image](https://user-images.githubusercontent.com/17537000/39523520-448e715c-4e59-11e8-98bc-54b9680a88cb.png)

Maybe?

**Comment by sighmon** [comment]
I've added the option to have an image background, but haven't tested it yet and don't have a placeholder in there.. more soon. https://github.com/sighmon/OpenDonation/commit/a8644af2ff9ed8ecb59e258334d128e3d8243e0c#diff-a04f098ad018a694226498c3121fee1dR54

**Comment by sighmon** [comment]
@ashleyhull-versent I've added logo & background colour options.

> To add your own custom logo to the top of the donation box, create a transparent .png image and copy it over the top of: app/src/main/res/drawable/custom_logo.png.
> 
> Then set the logo to appear in the file MainActivity.java by un-commenting out setCustomLogo();
> 
> To change the background colour, edit colorPrimary in app/src/main/res/values/colors.xml.
